//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvlaSmartSense.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartSenseEntities1 : DbContext
    {
        public SmartSenseEntities1()
            : base("name=SmartSenseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<errors> errors { get; set; }
        public virtual DbSet<fields> fields { get; set; }
        public virtual DbSet<readings> readings { get; set; }
        public virtual DbSet<sensors> sensors { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<langs> langs { get; set; }
    }
}
