USE [master]
GO
/****** Object:  Database [SmartSense]    Script Date: 5.12.2020 16:38:58 ******/
CREATE DATABASE [SmartSense]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartSense', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmartSense.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmartSense_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmartSense_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SmartSense] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartSense].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SmartSense] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SmartSense] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SmartSense] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SmartSense] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SmartSense] SET ARITHABORT OFF 
GO
ALTER DATABASE [SmartSense] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SmartSense] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SmartSense] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SmartSense] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SmartSense] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SmartSense] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SmartSense] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SmartSense] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SmartSense] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SmartSense] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SmartSense] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SmartSense] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SmartSense] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SmartSense] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SmartSense] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SmartSense] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SmartSense] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SmartSense] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SmartSense] SET  MULTI_USER 
GO
ALTER DATABASE [SmartSense] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SmartSense] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SmartSense] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SmartSense] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SmartSense] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SmartSense] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SmartSense] SET QUERY_STORE = OFF
GO
USE [SmartSense]
GO
/****** Object:  Table [dbo].[errors]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[errors](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RECORDTIME] [datetime] NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[DEVICEID] [varchar](50) NULL,
 CONSTRAINT [PK_errors] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[fields]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[fields](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[SENSORID] [int] NULL,
	[ALARMTEMP] [float] NULL,
 CONSTRAINT [PK_fields] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[langs]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[langs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
 CONSTRAINT [PK_langs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[readings]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[readings](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AIR_HUMIDITY] [float] NULL,
	[AIR_TEMPERATURE] [float] NULL,
	[RECORDTIME] [datetime] NULL,
	[DEVICEID] [varchar](50) NULL,
 CONSTRAINT [PK_readings] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sensors]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sensors](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEVICEID] [varchar](50) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[FIELDID] [int] NULL,
 CONSTRAINT [PK_sensors] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[settings]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[settings](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [nvarchar](50) NULL,
	[LASTNAME] [nvarchar](50) NULL,
	[PHONE] [nvarchar](50) NULL,
	[GSM] [nvarchar](50) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](250) NULL,
	[LANGSID] [int] NULL,
 CONSTRAINT [PK_settings] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 5.12.2020 16:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
	[FULLNAME] [varchar](250) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ACTIVE] [bit] NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SmartSense] SET  READ_WRITE 
GO
